"""Human-readable HTML rendering of skill results.

HTML is generated from the *same* Markdown each skill already produces, not
from a second set of templates. Two independent renderers would drift, and a
number appearing differently in the HTML than in the Markdown is exactly the
kind of discrepancy this project exists to avoid.

The converter handles only the closed set of Markdown constructs these skills
emit -- headings, bullets (one nesting level), pipe tables, bold, inline code,
paragraphs. It is not a general Markdown implementation and does not need to
be: the input is machine-generated by code in this package.

No external dependencies, no network, no remote assets. The output is a
single self-contained file.
"""

from __future__ import annotations

import re
from html import escape

_BOLD = re.compile(r"\*\*(.+?)\*\*")
_CODE = re.compile(r"`([^`]+)`")

STATUS_LABEL = {"ok": "完成", "degraded": "部分降級", "unavailable": "不可得"}


def _inline(text: str) -> str:
    """Escape, then apply inline formatting.

    Escaping first is deliberate: any ``<`` in the source becomes ``&lt;``
    before the formatting patterns run, so content can never introduce markup.
    ``**`` and backticks are untouched by escaping, so the patterns still match.
    """
    out = escape(text, quote=False)
    out = _BOLD.sub(r"<strong>\1</strong>", out)
    return _CODE.sub(r"<code>\1</code>", out)


def _render_table(rows: list[str]) -> str:
    """Render a pipe table, skipping the ``|---|`` separator row."""
    parsed = [[cell.strip() for cell in row.strip().strip("|").split("|")] for row in rows]
    body = [r for r in parsed[1:] if not all(set(c) <= set("-: ") for c in r)]

    head_html = "".join(f"<th>{_inline(c)}</th>" for c in parsed[0])
    body_html = "".join(
        "<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in row) + "</tr>" for row in body
    )
    return (
        '<div class="scroll"><table><thead><tr>'
        f"{head_html}</tr></thead><tbody>{body_html}</tbody></table></div>"
    )


def markdown_subset_to_html(markdown: str) -> str:
    """Convert the Markdown this package emits into an HTML fragment.

    Supports: ``#``/``##``/``###`` headings, ``-`` bullets with one level of
    two-space nesting, pipe tables, ``**bold**``, ``` `code` ```, and blank-line
    separated paragraphs. A paragraph that is entirely bold is treated as a
    sub-heading, which is how the limitations block is marked up.
    """
    html: list[str] = []
    bullets: list[tuple[int, str]] = []
    table: list[str] = []
    paragraph: list[str] = []

    def flush_bullets() -> None:
        if not bullets:
            return
        html.append("<ul>")
        depth = 0
        for level, text in bullets:
            while level > depth:
                html.append("<ul>")
                depth += 1
            while level < depth:
                html.append("</ul>")
                depth -= 1
            html.append(f"<li>{_inline(text)}</li>")
        while depth > 0:
            html.append("</ul>")
            depth -= 1
        html.append("</ul>")
        bullets.clear()

    def flush_table() -> None:
        if table:
            html.append(_render_table(table))
            table.clear()

    def flush_paragraph() -> None:
        if not paragraph:
            return
        joined = " ".join(paragraph)
        stripped = joined.strip()
        if stripped.startswith("**") and stripped.endswith("**") and stripped.count("**") == 2:
            html.append(f'<h4 class="lim">{_inline(stripped[2:-2])}</h4>')
        else:
            html.append(f"<p>{_inline(joined)}</p>")
        paragraph.clear()

    def flush_all() -> None:
        flush_bullets()
        flush_table()
        flush_paragraph()

    for raw in markdown.splitlines():
        line = raw.rstrip()
        stripped = line.strip()

        if not stripped:
            flush_all()
            continue

        if stripped.startswith("|"):
            flush_bullets()
            flush_paragraph()
            table.append(stripped)
            continue
        flush_table()

        for hashes, tag in (("### ", "h3"), ("## ", "h2"), ("# ", "h1")):
            if stripped.startswith(hashes):
                flush_all()
                html.append(f"<{tag}>{_inline(stripped[len(hashes):])}</{tag}>")
                break
        else:
            indent = len(line) - len(line.lstrip(" "))
            if stripped.startswith("- "):
                flush_paragraph()
                bullets.append((1 if indent >= 2 else 0, stripped[2:]))
            else:
                flush_bullets()
                paragraph.append(stripped)

    flush_all()
    return "\n".join(html)


STYLESHEET = """
:root{
  --bg:#fbfbfa; --fg:#1a1a19; --muted:#6b6b68; --line:#e2e1dd; --card:#fff;
  --accent:#7c5cff; --accent-soft:#f0ecff; --code:#f4f3f0;
  --ok:#1f7a4d; --ok-soft:#e8f5ee; --warn:#9a6510; --warn-soft:#fdf5e6;
  --off:#6b6b68; --off-soft:#efeeea;
  --mono:ui-monospace,SFMono-Regular,"Cascadia Mono",Menlo,Consolas,monospace;
}
@media (prefers-color-scheme:dark){
  :root{
    --bg:#16161a; --fg:#e8e8e6; --muted:#9c9c98; --line:#2e2e34; --card:#1e1e23;
    --accent:#a996ff; --accent-soft:#26213d; --code:#242429;
    --ok:#5cc98f; --ok-soft:#16301f; --warn:#e0b062; --warn-soft:#2c2415;
    --off:#9c9c98; --off-soft:#26262b;
  }
}
*{box-sizing:border-box}
body{
  margin:0; background:var(--bg); color:var(--fg);
  font-family:"Noto Sans TC","PingFang TC","Microsoft JhengHei",system-ui,sans-serif;
  line-height:1.75; font-size:16px; overflow-x:hidden;
}
.wrap{max-width:900px; margin:0 auto; padding:48px 24px 80px}
h1{font-size:clamp(24px,4vw,32px); margin:0 0 8px; letter-spacing:-.01em}
h2{font-size:20px; margin:48px 0 12px; padding-bottom:6px; border-bottom:1px solid var(--line)}
h3{font-size:17px; margin:0 0 10px}
h4.lim{
  font-size:12px; letter-spacing:.08em; color:var(--warn);
  margin:18px 0 6px; text-transform:uppercase;
}
p{margin:0 0 12px}
ul{margin:0 0 12px; padding-left:22px}
li{margin-bottom:5px}
li>ul{margin-top:5px}
code{font-family:var(--mono); font-size:.875em; background:var(--code); padding:.12em .4em; border-radius:4px}
.meta{color:var(--muted); font-size:14px; margin:0 0 4px}
.meta code{font-size:.9em}
.scroll{overflow-x:auto; margin:0 0 16px; border:1px solid var(--line); border-radius:10px; background:var(--card)}
table{border-collapse:collapse; width:100%; font-size:14px; min-width:420px}
th,td{text-align:left; padding:9px 14px; border-bottom:1px solid var(--line); vertical-align:top}
th{
  font-size:12px; letter-spacing:.03em; color:var(--muted);
  text-transform:uppercase; white-space:nowrap; background:var(--bg);
}
tbody tr:last-child td{border-bottom:none}
.section{
  border:1px solid var(--line); border-left:3px solid var(--accent);
  border-radius:10px; background:var(--card); padding:20px 22px; margin:0 0 16px;
}
.section.is-degraded{border-left-color:var(--warn)}
.section.is-unavailable{border-left-color:var(--off)}
.section h3{display:flex; align-items:center; gap:10px; flex-wrap:wrap}
.badge{
  font-family:var(--mono); font-size:11px; letter-spacing:.06em;
  padding:2px 8px; border-radius:999px; white-space:nowrap; font-weight:600;
}
.badge.ok{background:var(--ok-soft); color:var(--ok)}
.badge.degraded{background:var(--warn-soft); color:var(--warn)}
.badge.unavailable{background:var(--off-soft); color:var(--off)}
.limitations{
  border-left:3px solid var(--warn); background:var(--warn-soft);
  border-radius:10px; padding:16px 20px; font-size:14.5px;
}
.limitations h2{border:none; margin:0 0 8px; font-size:16px}
footer{margin-top:40px; padding-top:20px; border-top:1px solid var(--line); font-size:13px; color:var(--muted)}
"""


def _document(title: str, body: str) -> str:
    return (
        "<!doctype html>\n"
        '<html lang="zh-Hant">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{escape(title)}</title>\n<style>{STYLESHEET}</style>\n"
        f'</head>\n<body>\n<div class="wrap">\n{body}\n</div>\n</body>\n</html>\n'
    )


def render_section_html(result) -> str:
    """One skill's section as a standalone HTML fragment, with a status badge."""
    status = result.status
    label = STATUS_LABEL.get(status, status)
    inner = markdown_subset_to_html(result.section_markdown)
    badge = f'<span class="badge {escape(status)}">{escape(label)}</span>'

    # Attach the badge to the section heading the converter produced.
    if "</h3>" in inner:
        inner = inner.replace("</h3>", f"{badge}</h3>", 1)
    else:
        inner = badge + inner

    return f'<section class="section is-{escape(status)}">\n{inner}\n</section>'


def render_report_html(bundle, results) -> str:
    """A complete, self-contained HTML document for one asset."""
    as_of = bundle.as_of.isoformat() if bundle.as_of else "不可得"
    years = bundle.bars / 365

    coverage_rows = "".join(
        f"<tr><td><code>{escape(r.skill_id)}</code></td><td>{escape(r.skill_name)}</td>"
        f'<td><span class="badge {escape(r.status)}">'
        f"{escape(STATUS_LABEL.get(r.status, r.status))}</span></td></tr>"
        for r in results
    )

    limitations: list[str] = []
    for result in results:
        for item in result.limitations:
            entry = f"（{result.skill_id}）{item}"
            if entry not in limitations:
                limitations.append(entry)
    limitation_items = "".join(f"<li>{_inline(item)}</li>" for item in limitations)

    sections = "\n".join(render_section_html(r) for r in results)

    body = (
        f"<h1>{escape(bundle.asset)} 價格資料分析</h1>\n"
        f'<p class="meta">分析基準日（as_of）：<code>{escape(as_of)}</code></p>\n'
        f'<p class="meta">可用 K 線：{bundle.bars} 根（約 {years:.1f} 年）</p>\n'
        f'<p class="meta">資料來源類型：<code>public_market_data</code></p>\n'
        "<h2>產出覆蓋狀態</h2>\n"
        '<div class="scroll"><table><thead><tr><th>產出</th><th>名稱</th><th>狀態</th></tr>'
        f"</thead><tbody>{coverage_rows}</tbody></table></div>\n"
        "<h2>分析產出</h2>\n"
        f"{sections}\n"
        f'<div class="limitations"><h2>總體限制與揭露</h2><ul>{limitation_items}</ul></div>\n'
        "<footer><p>本文所有數值由決定性計算產生，未經模型生成或調整；"
        "相同輸入與相同 as_of 可完整重現。</p>"
        "<p>本文僅描述市場資料所呈現的狀態，不對任何交易或決策提供指引。</p></footer>"
    )

    from .lint import assert_no_advice

    return assert_no_advice(_document(f"{bundle.asset} 價格資料分析", body))
